resources:
- https://github.com/GoogleCloudPlatform/otlp-k8s-ingest//k8s/base/?ref=v0.2.0
- ticket-service.yaml
- reservation-service.yaml
- event-service.yaml
- gateway.yaml
- internal-gateway.yaml
configMapGenerator:
- name: client.properties
  files:
  - appConfig/client.properties 
- name: ticket-service.producer.properties
  files:
  - appConfig/ticket-service/producer.properties 
- name: ticket-service.stream.properties
  files:
  - appConfig/ticket-service/stream.properties 
- name: event-service.stream.properties
  files:
  - appConfig/event-service/stream.properties 
