apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-deployment
  labels:
    app: event-service 
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: event-service 
    spec:
      containers:
        - name: event-service
          resources:
            requests:
              memory: "2G"
              cpu: "500m"

