apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service-deployment
  labels:
    app: ticket-service 
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: ticket-service 
    spec:
      containers:
        - name: ticket-service
          resources:
            requests:
              memory: "8G"
              cpu: "4000m"
