apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service-deployment
  labels:
    app: event-service 
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: event-service 
    spec:
      containers:
        - name: event-service
          image: asia-east1-docker.pkg.dev/ticket-master-tall15421542/ticket-master/service:v0.0.23
          resources:
            requests:
              memory: "2G"
              cpu: "1000m"

