apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service-deployment
  labels:
    app: reservation-service 
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: reservation-service 
    spec:
      containers:
        - name: reservation-service
          image: asia-east1-docker.pkg.dev/ticket-master-tall15421542/ticket-master/service:v0.0.23
          resources:
            requests:
              memory: "4G"
              cpu: "2000m"

